<a href="https://colab.research.google.com/github/garcia-rhom/Walmart-Sales-Data-Analysis/blob/main/walmart_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Import Dependencies

In [33]:
import pandas as pd
import numpy as np

# 2. Initial Data Exploration

In [34]:
df = pd.read_csv('/content/drive/MyDrive/Data Analysis/Datasets/walmart.csv')
df

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48
...,...,...,...,...,...,...,...,...,...,...,...
10046,9996,WALM056,Rowlett,Fashion accessories,$37,3.0,03/08/23,10:10:00,Cash,3.0,0.33
10047,9997,WALM030,Richardson,Home and lifestyle,$58,2.0,22/02/21,14:20:00,Cash,7.0,0.48
10048,9998,WALM050,Victoria,Fashion accessories,$52,3.0,15/06/23,16:00:00,Credit card,4.0,0.48
10049,9999,WALM032,Tyler,Home and lifestyle,$79,2.0,25/02/21,12:25:00,Cash,7.0,0.48
10050,10000,WALM069,Rockwall,Fashion accessories,$62,3.0,26/09/20,9:48:00,Cash,3.0,0.33

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [36]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [37]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [38]:
df[df['unit_price'].isnull()]

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
1892,1893,WALM024,Carrollton,Home and lifestyle,NaN,NaN,09/06/23,16:09:00,Ewallet,9.0,0.48
1893,1894,WALM009,Plano,Fashion accessories,NaN,NaN,02/08/22,22:11:00,Ewallet,4.0,0.48
1894,1895,WALM010,Laredo,Home and lifestyle,NaN,NaN,01/08/23,12:06:00,Ewallet,4.0,0.48
1895,1896,WALM069,Rockwall,Fashion accessories,NaN,NaN,21/07/23,15:49:00,Ewallet,4.0,0.33
1896,1897,WALM093,Angleton,Home and lifestyle,NaN,NaN,15/05/22,12:36:00,Ewallet,9.0,0.33
1897,1898,WALM098,Mineral Wells,Fashion accessories,NaN,NaN,01/11/23,10:08:00,Ewallet,4.0,0.18
1898,1899,WALM009,Plano,Home and lifestyle,NaN,NaN,01/10/21,13:05:00,Ewallet,6.0,0.48
1899,1900,WALM071,Lufkin,Fashion accessories,NaN,NaN,19/05/21,8:36:00,Ewallet,7.0,0.33
1900,1901,WALM090,Brownwood,Home and lifestyle,NaN,NaN,13/02/21,14:50:00,Ewallet,8.0,0.33
1901,1902,WALM067,Haltom City,Fashion accessories,NaN,NaN,15/05/22,19:20:00,Ewallet,8.0,0.33
1902,1903,WALM033,Pearland,Home and lifestyle,NaN,NaN,28/08/22,15:37:00,Ewallet,4.0,0.48
1903,1904,WALM018,Frisco,Fashion accessories,NaN,NaN,21/04/22,18:30:00,Ewallet,4.0,0.48
1904,1905,WALM076,Huntsville,Home and lifestyle,NaN,NaN,02/03/20,14:33:00,Ewallet,4.0,0.33
1905,1906,WALM010,Laredo,Fashion accessories,NaN,NaN,20/08/21,14:25:00,Ewallet,5.0,0.48
1906,1907,WALM030,Richardson,Home and lifestyle,NaN,NaN,14/12/23,18:12:00,Ewallet,8.0,0.48
1907,1908,WALM001,Houston,Fashion accessories,NaN,NaN,09/08/22,12:46:00,Ewallet,9.0,0.36
1908,1909,WALM096,Eagle Pass,Home and lifestyle,NaN,NaN,23/11/21,18:26:00,Ewallet,9.0,0.33
1909,1910,WALM085,Kerrville,Fashion accessories,NaN,NaN,24/08/22,11:53:00,Ewallet,4.0,0.33
1910,1911,WALM040,Edinburg,Home and lifestyle,NaN,NaN,27/07/20,21:38:00,Ewallet,9.0,0.48
1911,1912,WALM080,Nacogdoches,Fashion accessories,NaN,NaN,15/10/20,8:01:00,Ewallet,7.0,0.33
1912,1913,WALM068,Burleson,Home and lifestyle,NaN,NaN,31/07/23,9:20:00,Ewallet,6.0,0.33
1913,1914,WALM048,Harlingen,Fashion accessories,NaN,NaN,28/02/21,18:47:00,Ewallet,7.0,0.48
1914,1915,WALM018,Frisco,Home and lifestyle,NaN,NaN,19/04/23,16:12:00,Ewallet,7.0,0.48
1915,1916,WALM015,Grand Prairie,Fashion accessories,NaN,NaN,11/08/21,21:28:00,Ewallet,5.0,0.48
1916,1917,WALM041,Mission,Home and lifestyle,NaN,NaN,25/06/23,13:15:00,Ewallet,6.0,0.48
1917,1918,WALM045,Missouri City,Fashion accessories,NaN,NaN,11/01/20,10:27:00,Credit card,5.0,0.48
1918,1919,WALM011,Lubbock,Home and lifestyle,NaN,NaN,01/08/22,14:40:00,Ewallet,8.0,0.48
1919,1920,WALM052,Mansfield,Fashion accessories,NaN,NaN,09/04/21,12:04:00,Ewallet,5.0,0.57
1920,1921,WALM022,Mesquite,Home and lifestyle,NaN,NaN,21/03/20,18:16:00,Ewallet,6.0,0.48
1921,1922,WALM024,Carrollton,Fashion accessories,NaN,NaN,16/03/21,15:39:00,Ewallet,8.0,0.48
1922,1923,WALM070,Hurst,Home and lifestyle,NaN,NaN,30/10/20,18:39:00,Ewallet,5.0,0.33

In [39]:
for col in df.columns:
  print(f"Columns: {col}")
  print(df[col].unique())
  print()

Columns: invoice_id
[    1     2     3 ...  9998  9999 10000]

Columns: Branch
['WALM003' 'WALM048' 'WALM067' 'WALM064' 'WALM013' 'WALM026' 'WALM088'
 'WALM100' 'WALM066' 'WALM065' 'WALM035' 'WALM027' 'WALM031' 'WALM008'
 'WALM029' 'WALM061' 'WALM053' 'WALM044' 'WALM083' 'WALM023' 'WALM001'
 'WALM072' 'WALM046' 'WALM012' 'WALM075' 'WALM076' 'WALM098' 'WALM021'
 'WALM096' 'WALM022' 'WALM095' 'WALM041' 'WALM070' 'WALM030' 'WALM033'
 'WALM079' 'WALM042' 'WALM036' 'WALM056' 'WALM058' 'WALM015' 'WALM063'
 'WALM089' 'WALM093' 'WALM045' 'WALM005' 'WALM078' 'WALM037' 'WALM069'
 'WALM087' 'WALM020' 'WALM007' 'WALM017' 'WALM094' 'WALM071' 'WALM090'
 'WALM097' 'WALM043' 'WALM011' 'WALM049' 'WALM040' 'WALM034' 'WALM014'
 'WALM004' 'WALM057' 'WALM055' 'WALM038' 'WALM025' 'WALM024' 'WALM085'
 'WALM016' 'WALM018' 'WALM068' 'WALM002' 'WALM062' 'WALM052' 'WALM047'
 'WALM054' 'WALM099' 'WALM074' 'WALM028' 'WALM019' 'WALM084' 'WALM039'
 'WALM060' 'WALM073' 'WALM059' 'WALM086' 'WALM050' 'WALM081' 'WALM009'
 'WALM077' 'WALM091' 'WALM051' 'WALM010' 'WALM032' 'WALM082' 'WALM006'
 'WALM092' 'WALM080']

Columns: City
['San Antonio' 'Harlingen' 'Haltom City' 'Bedford' 'Irving' 'Denton'
 'Cleburne' 'Canyon' 'Grapevine' 'Texas City' 'San Angelo' 'Abilene'
 'Lewisville' 'Corpus Christi' 'Round Rock' 'Cedar Park' 'Conroe' 'Pharr'
 'Farmers Branch' 'Midland' 'Houston' 'Lancaster' 'Temple' 'Garland'
 'San Marcos' 'Huntsville' 'Mineral Wells' 'McAllen' 'Eagle Pass'
 'Mesquite' 'Big Spring' 'Mission' 'Hurst' 'Richardson' 'Pearland'
 'La Porte' 'Bryan' 'Allen' 'Rowlett' 'Port Arthur' 'Grand Prairie'
 'Georgetown' 'Southlake' 'Angleton' 'Missouri City' 'Fort Worth'
 'Del Rio' 'League City' 'Rockwall' 'Waxahachie' 'Killeen' 'Arlington'
 'McKinney' 'Alamo' 'Lufkin' 'Brownwood' 'Alice' 'Baytown' 'Lubbock'
 'North Richland Hills' 'Edinburg' 'College Station' 'Amarillo' 'Austin'
 'Euless' 'Sugar Land' 'Waco' 'Carrollton' 'Kerrville' 'Brownsville'
 'Frisco' 'Burleson' 'Dallas' 'Galveston' 'Mansfield' 'Flower Mound'
 'Sherman' 'Weatherford' 'Weslaco' 'Odessa' 'Pasadena' 'Schertz'
 'Longview' 'DeSoto' 'Seguin' 'Pflugerville' 'Rosenberg' 'Victoria'
 'Friendswood' 'Plano' 'Coppell' 'Little Elm' 'New Braunfels' 'Laredo'
 'Tyler' 'El Paso' 'Lake Jackson' 'Nacogdoches']

Columns: category
['Health and beauty' 'Electronic accessories' 'Home and lifestyle'
 'Sports and travel' 'Food and beverages' 'Fashion accessories']

Columns: unit_price
['$74.69' '$15.28' '$46.33' ... '$74' '$60' nan]

Columns: quantity
[ 7.  5.  8.  6. 10.  2.  3.  4.  1.  9. nan]

Columns: date
['05/01/19' '08/03/19' '03/03/19' ... '18/04/22' '16/05/22' '25/07/20']

Columns: time
['13:08:00' '10:29:00' '13:23:00' ... '14:07:00' '7:51:00' '12:59:00']

Columns: payment_method
['Ewallet' 'Cash' 'Credit card']

Columns: rating
[ 9.1  9.6  7.4  8.4  5.3  4.1  5.8  8.   7.2  5.9  4.5  6.8  7.1  8.2
  5.7  4.6  6.9  8.6  4.4  4.8  5.1  9.9  6.   8.5  6.7  7.7  7.5  7.
  4.7  7.6  7.9  6.3  5.6  9.5  8.1  6.5  6.1  6.6  5.4  9.3 10.   6.4
  4.3  4.   8.7  9.4  5.5  8.3  7.3  4.9  4.2  9.2  7.8  5.2  9.   8.8
  6.2  9.8  9.7  5.   8.9  3. ]

Columns: profit_margin
[0.48 0.33 0.18 0.57 0.36 0.21]

# 3. Data Cleaning

## **a. Inconsistent column name formatting**

In [40]:
print(df.columns)

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [41]:
df.columns = df.columns.str.lower()
print(df.columns)

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

## **b. Incorrect data type for date and time columns**

In [42]:
df['datetime'] = pd.to_datetime(df['date'] + ' ' + df['time'].astype(str))
df.drop(columns=['time', 'date'], inplace=True)
df = df[[*df.columns[:6], 'datetime', *df.columns[6:-1]]]
df.info()

/tmp/ipython-input-1823529199.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['datetime'] = pd.to_datetime(df['date'] + ' ' + df['time'].astype(str))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   branch          10051 non-null  object
 2   city            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   datetime        10051 non-null  datetime64[ns]
 7   payment_method  10051 non-null  object
 8   rating          10051 non-null  float64
 9   profit_margin   10051 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 785.4+ KB

## **c. 31 null values in the unit_price and quantity columns.**

In [43]:
overall_null_percentage = df.isnull().sum().sum() / df.size * 100
print(f"Overall null percentage: {overall_null_percentage:.2f}%")

Overall null percentage: 0.06%

In [44]:
df = df.dropna()
df.isnull().sum()

invoice_id        0
branch            0
city              0
category          0
unit_price        0
quantity          0
datetime          0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [45]:
df.shape
df

,invoice_id,branch,city,category,unit_price,quantity,datetime,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,2019-05-01 13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,2019-08-03 10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,2019-03-03 13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,2019-01-27 20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,2019-08-02 10:37:00,Ewallet,5.3,0.48
...,...,...,...,...,...,...,...,...,...,...
10046,9996,WALM056,Rowlett,Fashion accessories,$37,3.0,2023-03-08 10:10:00,Cash,3.0,0.33
10047,9997,WALM030,Richardson,Home and lifestyle,$58,2.0,2021-02-22 14:20:00,Cash,7.0,0.48
10048,9998,WALM050,Victoria,Fashion accessories,$52,3.0,2023-06-15 16:00:00,Credit card,4.0,0.48
10049,9999,WALM032,Tyler,Home and lifestyle,$79,2.0,2021-02-25 12:25:00,Cash,7.0,0.48
10050,10000,WALM069,Rockwall,Fashion accessories,$62,3.0,2020-09-26 09:48:00,Cash,3.0,0.33

# 4. Export cleaned dataset as csv

In [46]:
df.to_csv('/content/drive/MyDrive/Data Analysis/Datasets/walmart_cleaned.csv')